Add  dutch translation
piitaya/lovelace-mushroom pull request #224
Opened 2022-04-02 05:48 UTC by Metal-Eagle

Added dutch translation

2022-04-02 10:24 UTC, piitaya requested changes
Can you fix the conflict with the main branch ? It's good for me, I will merge when it's done 🙂

2022-04-02 10:24 UTC, piitaya commented on src/localize.ts
> +    "nl": nl,
```suggestion
    nl,
```
No need to repeat the `nl` key.

2022-04-02 21:26 UTC, thibmaek commented
As a native Dutch speaker lots of these seem incorrect to me. 
For example:
- laatste gewijzigd should be laatst gewijzigd
- horizontaal layout should be horizontale layout
- justify is uitlijnen in dutch

2022-04-03 05:38 UTC, Metal-Eagle commented on src/localize.ts
> +    "nl": nl,
I edited this, it should look better now.

2022-04-03 09:22 UTC, piitaya approved these changes

2022-04-03 09:23 UTC, merged