Feature/graph card
piitaya/lovelace-mushroom pull request #308
Opened 2022-04-14 14:32 UTC by acesyde

![image](https://user-images.githubusercontent.com/958435/163412329-8d355650-e8ed-4c77-91cf-9a709f229a44.png)
![image](https://user-images.githubusercontent.com/958435/163412430-7d21597a-d067-4270-80fa-e90b27e359cb.png)

2022-04-14 16:29 UTC, piitaya commented
Nice 🙂 What's the graph height ? It should be nice to have a `46px` to have the size of the slider, buttons, etc... 
Or we can propose an option to let the user choose the size : compact vs default.

What do you think ?

2022-04-15 18:09 UTC, acesyde commented
@piitaya ready to review

2022-04-16 07:44 UTC, oziee commented
@acesyde you are a champ!!!! supper work helping to add so much to the work @piitaya has done.. fantastic good you guys

2022-04-20 07:49 UTC, Kahera commented on src/utils/form/ha-selector.ts
> +=======
You've got some conflict markers here

2022-04-21 08:00 UTC, alessandroias commented
Wouldn't it be more in line with the rest of the cards if name and value were reversed?
In mushroom usually the `primary_information` is name of the card, while the `secondary_information` is the entity state. I hate to point this out, as I am eager to use this card in my dashboard.

2022-04-21 08:19 UTC, alessandroias requested changes

2022-04-21 08:19 UTC, alessandroias commented on docs/cards/graph.md
> +| `entity`            | string | Required    | Vacuum entity                                  |
You don't want `Vacuum` in here.

2022-04-21 08:30 UTC, alessandroias approved these changes
Looks good to me!

2022-04-22 16:02 UTC, alessandroias commented
@piitaya what do you think about this?

2022-05-08 18:32 UTC, piitaya commented
I will merge it into a `graph` branch and test it before release 🙂

2022-05-08 18:33 UTC, merged

2022-05-08 18:40 UTC, acesyde commented
Yes because it's not up to date 🙂