feat(input-number-card)
piitaya/lovelace-mushroom pull request #676
Opened 2022-08-02 19:07 UTC by RonNabuurs

## Description
This pull request will add an input-number card. 

## Related Issue
https://github.com/piitaya/lovelace-mushroom/issues/230

## Motivation and Context
I needed this for my automation of sprinklers. I have an input_number card for the time the sprinklers will turn on.

## How Has This Been Tested
I have tested this on my own Home Assistant installation and locally with a docker container

## Types of changes
- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 🌎 Translation (addition or update a translation)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have tested the change locally.

2022-08-31 13:14 UTC, Misiu commented
@RonNabuurs can you add a screenshot showing the card like in similar PR's?

2022-09-01 17:07 UTC, RonNabuurs commented
@Misiu I've added a few images. Though I found out that there was already a [number-input module](https://github.com/piitaya/lovelace-mushroom/blob/main/src/shared/input-number.ts). So maybe I need to update this MR to reuse a lot of that code.

2022-10-11 07:30 UTC, piitaya requested changes
Thank you for the contribution. I was a little busy so I didn't take time for review 😅

Can you add `number` support ? I think it can be nice to have it too 🙂
And the component can be renamed `number-card` instead of `input_number-card`.

You can also add example in the showcase yaml file.

2022-10-11 07:30 UTC, piitaya commented on src/cards/input-number-card/const.ts
> +export const INPUT_NUMBER_ENTITY_DOMAINS = ["input_number"];
`number` domain should be supported as well

2022-11-06 23:24 UTC, spuljko commented on src/cards/input-number-card/const.ts
> +export const INPUT_NUMBER_ENTITY_DOMAINS = ["input_number"];
It would be nice that this card works not just for input_number domain, but for setting other numeric values. For example appliances like sous vide and air fryer target temperature/time.

2022-11-07 07:00 UTC, piitaya commented on src/cards/input-number-card/const.ts
> +export const INPUT_NUMBER_ENTITY_DOMAINS = ["input_number"];
@spuljko What's the type of the entities you want to add support ?

2022-11-13 07:10 UTC, spuljko commented on src/cards/input-number-card/const.ts
> +export const INPUT_NUMBER_ENTITY_DOMAINS = ["input_number"];
> @spuljko What's the type of the entities you want to add support ?

I was thinking about it, and came to counlusion that it would be better to add slider as option in template card. I will create new feature request for that.

2022-11-13 09:21 UTC, piitaya commented on src/cards/input-number-card/const.ts
> +export const INPUT_NUMBER_ENTITY_DOMAINS = ["input_number"];
We can't add the slider. It will add too much fields on the template card editor. Why people would need to build a custom slider ?

2022-11-13 11:47 UTC, spuljko commented on src/cards/input-number-card/const.ts
> +export const INPUT_NUMBER_ENTITY_DOMAINS = ["input_number"];
As I've said, appliances like air fryer, kettle, rice cooker, sous vide. There are two numbers that can be set: cooking time and temperature. Then there is humidity for dehumidifiers, watering time for splinkers, position for smart bed, and lots of other uses. Making separate card for all of that would take lot of time, but having slider that can call some service would do the job.

2022-11-23 16:59 UTC, AndrewSpec commented
Why it's still not merged?

2022-11-23 18:36 UTC, piitaya commented
Because changes have been requested.

2022-12-01 12:52 UTC, DannyFeliz commented
@piitaya, why don't you take over and fix the requested change?

2022-12-06 20:56 UTC, PaoloTK commented
I hope I didn't step on any toes by doing this but since I needed the number card myself I implemented the requested fixes here:
https://github.com/piitaya/lovelace-mushroom/tree/21e7545fead0bb7213d687084fcacfdb693a207e

Also, since number and input_number are generic entities I thought it useful to add the ability to set a custom slider color. The ability to set a custom icon and slider color is here:
https://github.com/piitaya/lovelace-mushroom/tree/d4d66736de0bc395058f03eec90865b519760d09

2023-01-22 23:09 UTC, tungmeister commented
Any progress on this one? It's the last thing I need to replace with a mushroom card on my mobile UI.

2023-02-02 17:40 UTC, jvuotila commented
Please, merge this to master. 🙏🏻

2023-02-27 13:35 UTC, merged

2023-02-27 13:47 UTC, piitaya commented
> @piitaya, why don't you take over and fix the requested change?

I suggested some changes but the author didn't respond. Each contributor is responsible for his/her PR. It's not my job to fix others work.

For this one, I fixed the missing points (documentation, yaml showcase example, number domain supports) because of the high demand. I also added icon color and display mode (slider or buttons).

2023-02-27 13:47 UTC, piitaya commented
@DannyFeliz I suggested some changes but the author didn't respond. Each contributor is responsible for his/her PR. It's not my job to fix others work.

For this one, I fixed the missing points (documentation, yaml showcase example, number domain supports) because of the high demand. I also added icon color and display mode (slider or buttons).

2023-03-01 15:11 UTC, bobloadmire commented
does this have the ability to change step sizes? i'd like to be able to snap to 5% increments for example.

2023-03-01 15:35 UTC, bobloadmire commented
Well that sucks because I can't change that. The Number Box card on HACS allows for this and works great but doesn't match the theme

2023-03-01 15:40 UTC, RonNabuurs commented
You can define the number in the configuration yaml of home-assistant

```yaml
input_number:
  slider:
    name: Your number
    initial: 30
    step: 30
    min: 0
    max: 240
    unit_of_measurement: Minutes
```

That would solve your problem right?

2023-03-12 10:46 UTC, gbcatrinoiu commented
does anyone have any idea why I do not see this card after updating the mushroom integration?