Add support for tilt position slider in `CoverCard`
piitaya/lovelace-mushroom pull request #739
Opened 2022-09-22 12:12 UTC by Atokulus

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested

## Types of changes

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 🌎 Translation (addition or update a translation)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have tested the change locally.

2022-09-23 19:25 UTC, piitaya commented
Thanks for the PR.
I think we should find an other way to show the difference between tilt and position slider. It looks buggy to have a curved one.

2022-09-25 17:10 UTC, Atokulus commented
Dear @piitaya 
Thanks for checking it out. I agree with you, that the wide curved slider might be too similar to the regular one, and the hard corners are quite nasty looking. Yet I believe we should stick with the curvature concept:
1. The curvature resembles and reflects the tilt rotation in a quite nice way, so the user can remember/guess the meaning of the tilt control.
2. The slider is quite large so the user has fine control over the tilt, yet it integrates nicely with the existing patterns (no complicate or hidden controls for ease of access).

Therefore I have already implemented another proposal using a thinner, rounded SVG path. I guess this looks more promising.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/1159506/192156154-d4a32b98-b784-4927-b97b-4042bae36097.png">

Best regards
Markus

2022-09-25 19:35 UTC, piitaya commented
I think we must keep the current slider design but may be change the background like color slider or color temp slider.

2022-09-25 22:28 UTC, Atokulus commented
Dear @piitaya 
Maybe some line pattern that gets denser to 100% would do?
Best regards
Markus

2022-09-26 12:32 UTC, Atokulus commented
Dear @piitaya
This is my new proposal:

<img width="380" alt="image" src="https://user-images.githubusercontent.com/1159506/192276839-2947d5f0-dfb7-476b-8948-ec6aa62f7871.png">

Best regards
Markus

2022-10-11 07:23 UTC, piitaya requested changes

2022-10-11 07:23 UTC, piitaya commented on src/cards/cover-card/controls/cover-tilt-position-control.ts
> +}
It must be computed one time instead of having a function called at each render.

2022-10-11 07:23 UTC, piitaya commented on src/cards/cover-card/cover-card.ts
> +
It's not needed as the tilt position is not displayed in the state.

2022-10-11 07:23 UTC, piitaya commented on src/cards/cover-card/cover-card.ts
> +                const color = getTiltStateColor(entity as CoverEntity);
```suggestion
                const color = getStateColor(entity as CoverEntity);
```
The same color should be used for the control. No need to have a separate function and new css variables.

2022-10-11 07:23 UTC, piitaya commented on src/shared/curved-slider.ts
> +import { css, CSSResultGroup, html, svg, LitElement, PropertyValues, TemplateResult } from "lit";
This file can be deleted

2022-10-11 07:23 UTC, piitaya commented on src/utils/theme.ts
> +
Can be deleted

2022-10-11 07:23 UTC, piitaya commented on src/utils/theme.ts
> +
Can be deleted

2022-10-12 09:00 UTC, Atokulus commented on src/cards/cover-card/controls/cover-tilt-position-control.ts
> +}
Ok. Was assuming as it is in `static get styles(): CSSResultGroup;`, this would be evaluated only once nonetheless.

2022-10-12 09:20 UTC, Atokulus commented on src/cards/cover-card/controls/cover-tilt-position-control.ts
> +}
No problem ;)

2022-10-12 09:23 UTC, Atokulus commented on src/cards/cover-card/cover-card.ts
> +                const color = getTiltStateColor(entity as CoverEntity);
I removed `tiltStateColor`. Let's see how people use it, and maybe there isn't any difference in perception ;)

2022-10-12 09:24 UTC, Atokulus commented on src/cards/cover-card/cover-card.ts
> +
Removed

2022-10-12 09:24 UTC, Atokulus commented on src/cards/cover-card/controls/cover-tilt-position-control.ts
> +}
Evaluate GRADIENT as const nonetheless

2022-10-12 09:24 UTC, Atokulus commented on src/shared/curved-slider.ts
> +import { css, CSSResultGroup, html, svg, LitElement, PropertyValues, TemplateResult } from "lit";
Deleted

2022-10-12 09:25 UTC, Atokulus commented on src/utils/theme.ts
> +
Deleted

2022-10-12 09:25 UTC, Atokulus commented on src/utils/theme.ts
> +
Deleted

2022-10-24 12:54 UTC, merged

2022-10-27 11:11 UTC, acseven commented
Thanks for this addition, but would it be feasible to control the tilt angle without having a specific blinds tilt control (for example Shelly 2.5) and maybe using a time span for calculation of the blinds position?

2023-03-23 19:49 UTC, piitaya commented
@zylxpl We don't have this information so we can adapt the UI 😞

@Atokulus Is your cover open at 0 and closed at 100?

2023-03-30 15:58 UTC, zylxpl commented
@piitaya What information? This should be user configurable, simple switch to alter the slider to smth like this:
![image](https://user-images.githubusercontent.com/13242378/228895040-a8549d4e-94be-4149-9db6-9db87f34331b.png)