Add battery badge to vacuum and cover
piitaya/lovelace-mushroom pull request #858
Opened 2022-11-18 11:04 UTC by marcgeurts

## Description
Added a renderBatteryBadge function for the vacuum and cover card

## Related Issue
[#844](https://github.com/piitaya/lovelace-mushroom/issues/844)

## Motivation and Context

## How Has This Been Tested

## Types of changes

-   [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
-   [ ] 🚀 New feature (non-breaking change which adds functionality)
-   [ ] 🌎 Translation (addition or update a translation)
-   [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [ ] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [ ] I have tested the change locally.
-   [ ] I followed [the steps](https://github.com/piitaya/lovelace-mushroom#maintainer-steps-to-add-a-new-language) if I add a new language .

2022-11-18 11:27 UTC, marcgeurts commented
@piitaya Do you want to review this before merging?

2022-11-18 12:30 UTC, piitaya commented
The proper way to have support battery in HA is to have an additional battery sensor linked to the device, not attributes.
Battery level is available as attributes from vacuum but not for cover and lock.

Also, what's the use case to display the battery level on the card? I think it will overloaded the card and dashboard.

2022-11-18 12:41 UTC, piitaya commented
Mushroom is focused on single entity. I do not prefer to offer too much options because the editor will look overloaded and it  more maintenance across updates.

2022-11-18 12:42 UTC, marcgeurts commented
How about if i remove it from the lock and cover card? and leave it on the vacuum card:
[#456](https://github.com/piitaya/lovelace-mushroom/issues/456)

2022-11-18 20:28 UTC, piitaya requested changes
I think we can add the battery badge for vacuum because it's official property (https://developers.home-assistant.io/docs/core/entity/vacuum/)

Also, how does it look with the animation ?

2022-11-18 20:28 UTC, piitaya commented on src/utils/base-card.ts
> +        const color = level > 40 ? "var(--rgb-success)" : level > 20 ? "var(--rgb-warning)" : "var(--rgb-danger)";
```suggestion
        const color = level >= 70 ? "var(--rgb-success)" : level >= 30 ? "var(--rgb-warning)" : "var(--rgb-danger)";
```
Home Assistant battery color rules for tile card. May be we can use the same values ?

2022-11-18 20:28 UTC, piitaya commented on src/utils/base-card.ts
> +    protected renderBatteryBadge(entity: HassEntity): TemplateResult | null {
This function should be moved to vacuum card because only vacuum support `battery_level` and `battery_icon`.

2022-11-18 20:28 UTC, piitaya commented on src/cards/vacuum-card/vacuum-card-config.ts
> +        display_battery: optional(boolean()),
```suggestion
        show_battery_icon: optional(boolean()),
```
Because we already have `show_conditons`, `show_temperature` for weather chip for example.

2022-11-18 20:28 UTC, piitaya commented on src/cards/vacuum-card/vacuum-card-editor.ts
> +                { name: "display_battery", selector: { boolean: {} } },
Why there is a empty field ?

2023-03-06 13:47 UTC, marcgeurts reviewed
I've removed the battery badge from lock and cover, it's now only added too the vacuum.

2023-03-06 13:47 UTC, marcgeurts commented on src/cards/vacuum-card/vacuum-card-editor.ts
> +                { name: "display_battery", selector: { boolean: {} } },
So it aligns with the other toggle (above it) on the right side.

2023-03-11 14:54 UTC, thor9898 commented
@marcgeurts Why removing the battery from locks?:(

2023-03-16 17:33 UTC, marcgeurts commented
@thor9898 As requested by @piitaya , because it's not supported by HA.

2023-06-16 11:39 UTC, piitaya requested changes

2023-06-16 11:39 UTC, piitaya commented on src/ha/data/entity.ts
> +}
This can be moved to `vacuum.ts`

2023-06-16 11:39 UTC, piitaya commented on docs/cards/vacuum.md
> +| `display_battery`   | boolean                                             | `false`     | Displays the battery level in a badge                                               |
Can we rename it to `show_battery_level`? We already have `show_temperature`, `show_volume_level`, etc...

2023-06-16 11:40 UTC, piitaya commented
I suggested some change before merging it 🙂

2024-02-28 15:43 UTC, closed without merging